name: cypress
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cypress:
    runs-on: cypress/included:13.2.0  # Puedes cambiar la imagen según tus necesidades

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Ejecutar pruebas de Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm cypress run 
