name: cypress/included:13.2.0

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cypress:
    runs-on: ubuntu-latest  # Puedes cambiar la imagen según tus necesidades

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas de Cypress
        run: npm cypress run 
